// This file will be generated by Supabase CLI
// For now, we'll define the types manually based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      trainers: {
        Row: {
          id: string
          name_ar: string
          name_he: string
          name_en: string
          phone: string
          role: 'admin' | 'sub_trainer'
          auth_user_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name_ar: string
          name_he: string
          name_en: string
          phone?: string
          role?: 'admin' | 'sub_trainer'
          auth_user_id?: string | null
          gender?: 'male' | 'female'
          availability?: string[]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name_ar?: string
          name_he?: string
          name_en?: string
          phone?: string
          role?: 'admin' | 'sub_trainer'
          auth_user_id?: string | null
          gender?: 'male' | 'female'
          availability?: string[]
          created_at?: string
          updated_at?: string
        }
      }
      halls: {
        Row: {
          id: string
          name_ar: string
          name_he: string
          name_en: string
          description_ar: string | null
          description_he: string | null
          description_en: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name_ar: string
          name_he: string
          name_en: string
          description_ar?: string | null
          description_he?: string | null
          description_en?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name_ar?: string
          name_he?: string
          name_en?: string
          description_ar?: string | null
          description_he?: string | null
          description_en?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      events: {
        Row: {
          id: string
          hall_id: string
          trainer_id: string | null
          type: 'game' | 'training'
          title_ar: string
          title_he: string
          title_en: string
          event_date: string
          start_time: string
          end_time: string
          recurrence_rule: string | null
          notes_ar: string | null
          notes_he: string | null
          notes_en: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          hall_id: string
          trainer_id?: string | null
          type: 'game' | 'training'
          title_ar: string
          title_he: string
          title_en: string
          event_date: string
          start_time: string
          end_time: string
          recurrence_rule?: string | null
          notes_ar?: string | null
          notes_he?: string | null
          notes_en?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          hall_id?: string
          trainer_id?: string | null
          type?: 'game' | 'training'
          title_ar?: string
          title_he?: string
          title_en?: string
          event_date?: string
          start_time?: string
          end_time?: string
          recurrence_rule?: string | null
          notes_ar?: string | null
          notes_he?: string | null
          notes_en?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      classes: {
        Row: {
          id: string
          name_ar: string
          name_he: string
          name_en: string
          trainer_id: string | null
          hall_id: string | null
          schedule_info: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name_ar: string
          name_he: string
          name_en: string
          trainer_id?: string | null
          hall_id?: string | null
          schedule_info?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name_ar?: string
          name_he?: string
          name_en?: string
          trainer_id?: string | null
          hall_id?: string | null
          schedule_info?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      trainees: {
        Row: {
          id: string
          name_ar: string
          name_he: string
          name_en: string
          phone: string | null
          jersey_number: number | null
          class_id: string | null
          is_paid: boolean
          amount_paid: number
          payment_date: string | null
          payment_comment_ar: string | null
          payment_comment_he: string | null
          payment_comment_en: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name_ar: string
          name_he: string
          name_en: string
          phone?: string | null
          jersey_number?: number | null
          class_id?: string | null
          is_paid?: boolean
          amount_paid?: number
          payment_date?: string | null
          payment_comment_ar?: string | null
          payment_comment_he?: string | null
          payment_comment_en?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name_ar?: string
          name_he?: string
          name_en?: string
          phone?: string | null
          jersey_number?: number | null
          class_id?: string | null
          is_paid?: boolean
          amount_paid?: number
          payment_date?: string | null
          payment_comment_ar?: string | null
          payment_comment_he?: string | null
          payment_comment_en?: string | null
          gender?: 'male' | 'female'
          created_at?: string
          updated_at?: string
        }
      }
      attendance: {
        Row: {
          id: string
          trainee_id: string
          event_id: string
          status: 'present' | 'absent' | 'late'
          marked_by: string | null
          marked_at: string
        }
        Insert: {
          id?: string
          trainee_id: string
          event_id: string
          status: 'present' | 'absent' | 'late'
          marked_by?: string | null
          marked_at?: string
        }
        Update: {
          id?: string
          trainee_id?: string
          event_id?: string
          status?: 'present' | 'absent' | 'late'
          marked_by?: string | null
          marked_at?: string
        }
      }
      payment_logs: {
        Row: {
          id: string
          trainee_id: string
          amount: number
          payment_date: string
          season: string | null
          note: string | null
          created_at: string
        }
        Insert: {
          id?: string
          trainee_id: string
          amount: number
          payment_date?: string
          season?: string | null
          note?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          trainee_id?: string
          amount?: number
          payment_date?: string
          season?: string | null
          note?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
